# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 635d25d0e17b7c0f4b54bbd331741d105435af5b42676dc877914cc47eaf4b5c7234a015435a09533f1effdd1f189f164b560b0e5e8cd62e203ccb0f2255bc55

test:
  secret_key_base: 511c79901b59bed44aa8e215c01e51c79feef149a3a110ee50cc2a974b9779173227dc8c35525095374cf486bfab2168e8d205d85742e64659c3b2ab3b91595d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
